### ISSUE TITLE
Inline style is persistent in this repo.

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/allay-fe#43]
https://github.com/Lambda-School-Labs/allay-fe/blob/64733fe2338c3cce7cd24b484e693617a58c7b57/src/components/Dashboard/AddCompanyForm.js#L61

This is just an example.
See if you can use a stylesheet instead.

**Comment by spencer-mcguire** [comment]
Inline is preferred with tailwind css and Chakra UI.

**Comment by noahfranco** [comment]
Labs_23 is using Chakra UI. Therefore, we will take note to only use inline styling when implementing Chakra.
